[versions]
kotlin = "2.4.0"
aws-sdk-kotlin = "1.6.92"
kotlinx-coroutines = "1.10.2"
s3overflow = "0.1.0"
kotlin-logging = "7.0.7"
slf4j = "2.0.17"
mockk = "1.14.9"
assertj = "3.27.7"
maven-publish = "0.37.0"
testcontainers = "1.21.4"
testcontainers-floci = "1.12.0"

[libraries]
aws-sdk-kotlin-sqs = { module = "aws.sdk.kotlin:sqs", version.ref = "aws-sdk-kotlin" }
aws-sdk-kotlin-s3 = { module = "aws.sdk.kotlin:s3", version.ref = "aws-sdk-kotlin" }
s3overflow = { module = "com.christoph-sens:s3overflow", version.ref = "s3overflow" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-floci = { module = "io.floci:testcontainers-floci", version.ref = "testcontainers-floci" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
