name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  # Shared job, see https://github.com/christoph-sens/ci-workflows
  auto-merge:
    uses: christoph-sens/ci-workflows/.github/workflows/dependabot-auto-merge.yml@dd2a323913c440d0f56c975a644ff0c408d141fb # v1.2.1
